config/routes.rb
Rails.application.routes.draw do
	resources :users
	resources :cats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
	

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
    has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :current_cat, only: [:show, :edit, :update, :destroy]

  def index
    @cats = Cat.all
  end

  def show

  end

  def new
    @cat = Cat.new
  end

  def create
    cat = Cat.create(cat_params)

    redirect_to cat_path(cat)
  end

  def edit

  end

  def update
    if @cat.avatar.attached?
      @cat.avatar.purge()
    end
    @cat.avatar.attach(params[:avatar])
    @cat.update(cat_params)

    redirect_to cat_path(@cat)
  end

  def destroy
    @cat.destroy

    redirect_to cats_path
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :motto, :age, :weight, :fur, :avatar)
  end

  def current_cat
    @cat = Cat.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/edit.html.erb
<head>
<style>
body {
    font-family: gotham;
}
h1 {
    color: #211382;
}
p {
    color: grey;
    font-size: 14px;
    margin: 10px; 
}

a {
    text-decoration: none;  
    color: #403e3e;
    text-align: center;
}

.home{
    font-size:12px;
}

img {
    width:  250px;
}
</style>
</head>


<h1>Cats#edit</h1>
<p>Find me in app/views/cats/edit.html.erb</p>
<h3>Update Cat Details</h3>
<%= form_with model: @cat do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :motto, placeholder: "motto" %>
  <%= form.text_field :weight, placeholder: "weight" %>
  <%= form.text_field :age, placeholder: "age" %>
  <%= form.text_field :fur, placeholder: "fur color" %>

<br>
  <h3><%= form.label "Edit Profile Photo"%></h3>
  <%= form.file_field :avatar %>
<br>
  <% if @cat.avatar.attached? %>
    <image src="<%=(url_for(@cat.avatar))%>">
<% end %>
<br>
  <%= form.submit %>
<% end %> 

app/views/cats/index.html.erb
<style>
body {
    font-family: gotham;
}
h1 {
    color: #cc1cb3;
}
p {
    color: grey;
    font-size: 14px;
    margin: 10px; 
}
.btn{
    width: 150px;
    /* height: 2px; */
    border-radius: 6px;
    margin: 10px 0px;
    background-color: #35323e;
    padding: 6px;
    text-align: center;
    color: white;
    font-size: 14px;
}
a {
    text-decoration: none;  
    text-align: center;
}
.home{
    font-size:12px;
}

</style>
</head>


<h1>Cat Adoption Agency</h1>
<p>Welcome to Camstar's Cat Adoption Agency. Find the perfect cat for you!</p>

<ul>
  <% @cats.each do |cat| %>
    <li><%= link_to cat.name, cat_path(cat)  %></li>
  <% end %>
</ul>

<a href="http://localhost:3000/cats/new/"> <div class="btn">
Register a Cat
</div></a>

app/views/cats/new.html.erb
<head>
<style>
body {
    font-family: gotham;
}
h1 {
    color: #211382;
}
p {
    color: grey;
    font-size: 14px;
    margin: 10px; 
}

a {
    text-decoration: none;  
    color: #403e3e;
    text-align: center;
}

.home{
    font-size:12px;
}
</style>
</head>

<div class="home">
<a href="http://localhost:3000/cats/"> < Back to Home</a>
</div>

<h1>Register a New Cat</h1>
<p>We will help you place your cat in a loving home with yummy food.</p>
<h3>Register a Cat</h3>
<%= form_with model: @cat do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :motto, placeholder: "motto" %>
  <%= form.text_field :weight, placeholder: "weight" %>
  <%= form.text_field :age, placeholder: "age" %>
  <%= form.text_field :fur, placeholder: "fur color" %>

  <%= form.label "Profile Photo"%>
  <%= form.file_field :avatar %>

  <%= form.submit %>
<% end %>

app/views/cats/show.html.erb
<head>
<style>
body {
    font-family: gotham;
}
h1 {
    color: #211382;
}
p {
    color: grey;
    font-size: 14px;
    margin: 10px; 
}
.rmv{
    width: 150px;
    /* height: 2px; */
    border-radius: 6px;
    margin: 10px 0px;
    background-color: #c9b5f7;
    padding: 6px;
    text-align: center;
    font-size: 14px;
}
a {
    text-decoration: none;  
    color: #403e3e;
    text-align: center;
}
.home{
    font-size:12px;
}

img {
    width:  250px;
}

h3{
    margin-top: 5px;
}

.main{
    padding: 8px;
    border-radius: 8px;
    border: 2px dotted #d4d4d4;
    width: 400px;
    text-align: left;
}
</style>
</head>
<div class="home">
<a href="http://localhost:3000/cats/"> < Back to Home</a>
</div>

<h1>Adopt Me</h1>
<p>I want to live in a nice home and eat yummy food</p>
<div class="main">
<h3>Name: <%= @cat.name %></h2>
<p>My Motto: "<%= @cat.motto %>"</p>
<p>Weight: "<%= @cat.weight %>"</p>
<p>Age: "<%= @cat.age %>"</p>
<p>Fur: "<%= @cat.fur %>"</p>
<% if @cat.avatar.attached? %>
    <image src="<%=(url_for(@cat.avatar))%>">
<% end %>
<div class="rmv">
   <%= link_to "Edit", edit_cat_path(@cat)  %>
</div>

<div class="rmv">
<%= link_to 'Remove', @cat, method: :delete, data: { confirm: 'Are you sure?'} %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul>
  <% @users.each do |user| %>
    <li><%= user.email %><%= user.password %><%= user.permission %><%= user.company %><%= user.company_sizee %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>